title: Ky4meru
description: A Camel\'s Diary
theme: just-the-docs

favicon_ico: "/assets/images/favicon.ico"

url: https://github.com/ky4meru/ky4meru.github.io

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue

footer_content: "Copyright &copy; 2023-2024 Ky4meru. Distributed by an <a href=\"https://github.com/ky4meru/ky4meru.github.io/blob/main/LICENSE\">MIT license.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y @ %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ky4meru/ky4meru.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

aux_links_new_tab: true